### ISSUE TITLE
Turn the "join us" into a larger CTA Button

### ISSUE THREAD

**Issue by phil-ociraptor** [phil-ociraptor/sos-landing#2]
The "Join us" link is tiny and not very obvious that it is a button. The goal of this task is to turn it into a beautiful button.

There is some design leeway here as well, so do your best to come up with something aesthetically pleasing! I recommend starting with the existing colors.

This task is mostly a CSS task, but also a task to get you up and running.

**Comment by kokosanki** [comment]
Hi, Can I work on this one?

**Comment by phil-ociraptor** [comment]
Hi there! These tickets are intended for [Summer of Shipping](https://summerofshipping.com/) participants. From your profile, I can't tell if you're a part of Summer of Shipping. 

That said, feel free to attempt the change - and if it looks good, I'll merge it in!

**Comment by kokosanki** [comment]
Sorry, I'm not a part of that, I was just searching for some open-source projects to contribute to, in order to get some experience with real projects, instead of just coding on my own. Btw. Summer of Shipping sounds great, is it still possible to join?

I'll leave this issue for the participants :)

**Comment by Zenahr** [comment]
> 
> 
> Sorry, I'm not a part of that, I was just searching for some open-source projects to contribute to, in order to get some experience with real projects, instead of just coding on my own. Btw. Summer of Shipping sounds great, is it still possible to join?
> 
> I'll leave this issue for the participants :)

Yes it is. Visit the homepage for more info: https://sos-landing.now.sh/

**Comment by alecbar** [comment]
Just created a pull request for this one, let me know what you think. Would love to keep contributing and be part of the team working on the site.
