### ISSUE TITLE
Add another CTA button next to "Join Us" called "Become a Mentor"

### ISSUE THREAD

**Issue by phil-ociraptor** [phil-ociraptor/sos-landing#7]
Our home page really has 2 primary CTAs - either "join us" as a student, or become a mentor. We want to encourage both.

Right now, the main CTA is "Join Us", but "Become a Mentor" is hidden down the page.

The goal of this task is to add a Secondary button next to Join us for "Become a Mentor". The "Become a Mentor" should link to https://forms.gle/ybJ7pdF5Q3axZbrbA

**Comment by kdmarble** [comment]
Just opened a PR for this
